import React,{useEffect,useMemo,useState}from'react';
import{neon}from'./lib/neonClient';

const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const statusLabel=s=>({EM_ANALISE:'EM ANÁLISE',APROVADO:'APROVADO',ATIVO:'ATIVO',ATRASADO:'ATRASADO',PAGO:'PAGO',RECUSADO:'RECUSADO'}[s]||s||'—');

export default function Admin({user}){
 const[users,setUsers]=useState([]),[loans,setLoans]=useState([]),[settings,setSettings]=useState({interest_rate:30,term_days:30,daily_late_fee:0}),[locations,setLocations]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setError('');const [u,l,s,loc]=await Promise.all([neon.from('crpay_users').select('*').order('created_at',{ascending:false}),neon.from('crpay_loans').select('*').order('requested_at',{ascending:false}),neon.from('crpay_settings').select('*').eq('id','global').limit(1),neon.from('crpay_location_history').select('*').order('captured_at',{ascending:false})]);if(u.error||l.error||s.error||loc.error)setError(u.error?.message||l.error?.message||s.error?.message||loc.error?.message||'Erro ao carregar painel.');if(!u.error)setUsers(u.data||[]);if(!l.error)setLoans(l.data||[]);if(!s.error&&s.data?.[0])setSettings(s.data[0]);if(!loc.error)setLocations(loc.data||[])}
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>({clientes:users.filter(x=>String(x.email).toLowerCase()!=='alissoncrpay@gmail.com').length,analise:loans.filter(x=>x.status==='EM_ANALISE').length,ativos:loans.filter(x=>x.status==='ATIVO'||x.status==='APROVADO').length,atrasados:loans.filter(x=>x.status==='ATRASADO').length,pagos:loans.filter(x=>x.status==='PAGO').length,total:loans.filter(x=>!['RECUSADO'].includes(x.status)).reduce((a,b)=>a+Number(b.principal||0),0)}),[users,loans]);
 async function setLoanStatus(id,status){setBusy(true);const r=await neon.from('crpay_loans').update({status,approved_at:status==='APROVADO'?new Date().toISOString():undefined}).eq('id',id).select();if(r.error)alert(r.error.message);await load();setBusy(false)}
 async function saveSettings(e){e.preventDefault();setBusy(true);const r=await neon.from('crpay_settings').update({interest_rate:Number(settings.interest_rate),term_days:Number(settings.term_days),daily_late_fee:Number(settings.daily_late_fee||0),updated_at:new Date().toISOString()}).eq('id','global').select();if(r.error)alert(r.error.message);await load();setBusy(false)}
 async function signOut(){await neon.auth.signOut();location.reload()}
 const latestLocByUser={};locations.forEach(x=>{if(!latestLocByUser[x.auth_uid])latestLocByUser[x.auth_uid]=x});
 return <div className="app admin-app"><header><div><small>ADMIN PRINCIPAL</small><h2>CRPay • Gestão</h2></div><button onClick={signOut}>Sair</button></header><main>
  <section className="hero"><span className="pill">ACESSO TOTAL</span><small>Administrador</small><h1>{user.email}</h1><div className="loan-grid"><div><small>Clientes</small><b>{stats.clientes}</b></div><div><small>Carteira</small><b>{money(stats.total)}</b></div></div></section>
  <div className="quick"><button><b>{stats.analise}</b><span>Em análise</span></button><button><b>{stats.ativos}</b><span>Ativos</span></button><button><b>{stats.atrasados}</b><span>Atrasados</span></button><button><b>{stats.pagos}</b><span>Pagos</span></button></div>
  {error&&<p className="error">{error}</p>}
  <section className="card"><h3>Configuração do crédito</h3><form onSubmit={saveSettings}><label>Juros padrão (%)<input type="number" value={settings.interest_rate??30} onChange={e=>setSettings({...settings,interest_rate:e.target.value})}/></label><label>Prazo padrão (dias)<input type="number" value={settings.term_days??30} onChange={e=>setSettings({...settings,term_days:e.target.value})}/></label><label>Multa diária<input type="number" step="0.01" value={settings.daily_late_fee??0} onChange={e=>setSettings({...settings,daily_late_fee:e.target.value})}/></label><button className="primary" disabled={busy}>Salvar regras</button></form></section>
  <section className="card"><h3>Solicitações e empréstimos</h3>{loans.length===0?<p>Nenhuma solicitação.</p>:loans.map(l=>{const borrower=users.find(u=>u.auth_uid===l.borrower_auth_uid);return <article className="loan" key={l.id}><div><b>{borrower?.name||borrower?.email||'Cliente'}</b><small>{money(l.principal)} • {Number(l.interest_rate||0)}% • {statusLabel(l.status)}</small></div><div className="row"><button className="primary" disabled={busy} onClick={()=>setLoanStatus(l.id,'APROVADO')}>Aprovar</button><button disabled={busy} onClick={()=>setLoanStatus(l.id,'RECUSADO')}>Recusar</button><button disabled={busy} onClick={()=>setLoanStatus(l.id,'PAGO')}>Pago</button></div></article>})}</section>
  <section className="card"><h3>Clientes e Score</h3>{users.filter(u=>String(u.email).toLowerCase()!=='alissoncrpay@gmail.com').map(u=>{const loc=latestLocByUser[u.auth_uid];const map=loc?`https://www.openstreetmap.org/?mlat=${loc.latitude}&mlon=${loc.longitude}#map=16/${loc.latitude}/${loc.longitude}`:null;return <article className="loan" key={u.id||u.auth_uid}><div><b>{u.name||u.email}</b><small>{u.email} • Score {u.score??500}/1000 • {u.status||'OK'}</small></div><div className="row"><span>{u.phone||'Sem telefone'}</span>{map?<a href={map} target="_blank" rel="noreferrer">📍 Ver mapa</a>:<span>Sem localização</span>}</div></article>})}</section>
 </main></div>
}
